source/main/urls.py
from django.contrib import admin
from django.urls import path

from webapp.views.answer_views import AnswerView
from webapp.views.choice_views import ChoiceForPollCreateView, ChoiceUpdateView, ChoiceDeleteView
from webapp.views.poll_views import IndexView, PollView, PollCreateView, PollUpdateView, PollDeleteView, StatisticView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('poll/<int:pk>/', PollView.as_view(), name='poll_view'),
    path('poll/add/', PollCreateView.as_view(), name='poll_add'),
    path('poll/<int:pk>/edit/', PollUpdateView.as_view(), name='poll_update'),
    path('poll/<int:pk>/delete/', PollDeleteView.as_view(), name='poll_delete'),
    path('poll/<int:pk>/add/', ChoiceForPollCreateView.as_view(), name='choice_add'),
    path('choice/<int:pk>/edit/', ChoiceUpdateView.as_view(), name='choice_update'),
    path('choice/<int:pk>/delete/', ChoiceDeleteView.as_view(), name='choice_delete'),
    path('poll/<int:pk>/answer/', AnswerView.as_view(), name='answer'),
    path('poll/<int:pk>/statistic/', StatisticView.as_view(), name='statistic'),
]

source/webapp/models.py
from django.db import models


class Poll(models.Model):
    question = models.TextField(max_length=200, null=False, blank=False, verbose_name='Вопрос')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.question


class Choice(models.Model):
    answer_option = models.TextField(max_length=200, null=False, blank=False, verbose_name='Вариант ответа')
    poll = models.ForeignKey('webapp.Poll', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Опрос',
                                 related_name='polls')

    def __str__(self):
        return self.answer_option


class Answer(models.Model):
    poll = models.ForeignKey('webapp.Poll', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Опрос',
                                 related_name='answer_poll')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    choice = models.ForeignKey('webapp.Choice', on_delete=models.CASCADE, null=False, blank=False, verbose_name='Вариант ответа',
                             related_name='answer_choice')

source/webapp/forms.py
from django import forms

from webapp.models import Poll, Choice, Answer


class PollForm(forms.ModelForm):
    class Meta:
        model = Poll
        exclude = ['created_at', 'updated_at']


class ChoicePollForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['answer_option']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = []

source/webapp/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views/answer_views.py
from django.shortcuts import render, redirect
from django.views import View
from webapp.models import Answer, Poll, Choice


class AnswerView(View):
    template_name = 'answer/answer.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['poll'] = Poll.objects.get(pk=kwargs['pk'])
        return render(request, self.template_name, context=context)


    def post(self, request, *args, **kwargs):
        choice_pk = request.POST.get('choice')
        choice = Choice.objects.get(pk=choice_pk)
        poll = Poll.objects.get(pk=kwargs['pk'])
        Answer.objects.create(poll=poll, choice=choice)
        return redirect('index')

source/webapp/views/choice_views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import ChoicePollForm
from webapp.models import Choice, Poll


class ChoiceForPollCreateView(CreateView):
    model = Choice
    template_name = 'choice/create.html'
    form_class = ChoicePollForm
    context_key = 'choice'

    def get_redirect_url(self):
        return reverse('poll_view', kwargs={'pk': self.object.poll.pk})

    def dispatch(self, request, *args, **kwargs):
        self.poll = self.get_poll()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.poll.polls.create(**form.cleaned_data)
        return redirect('poll_view', pk=self.poll.pk)

    def get_poll(self):
        poll_pk = self.kwargs.get('pk')
        return get_object_or_404(Poll, pk=poll_pk)


class ChoiceUpdateView(UpdateView):
    model = Choice
    template_name = 'choice/update.html'
    form_class = ChoicePollForm
    context_object_name = 'choice'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('poll_view', kwargs={'pk': self.object.poll.pk})


class ChoiceDeleteView(DeleteView):
    model = Choice
    template_name = 'choice/delete.html'
    context_object_name = 'choice'

    def get_success_url(self):
        return reverse('poll_view', kwargs={'pk': self.object.poll.pk})

source/webapp/views/poll_views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import PollForm, ChoicePollForm
from webapp.models import Poll, Answer


class IndexView(ListView):
    template_name = 'poll/index.html'
    context_object_name = 'polls'
    model = Poll
    ordering = ['-created_at']
    paginate_by = 5
    paginate_orphans = 1


class PollView(DetailView):
    template_name = 'poll/poll.html'
    model = Poll

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        poll = self.object
        context['form'] = ChoicePollForm()
        context['choices'] = poll.polls.all()
        return context


class PollCreateView(CreateView):
    form_class = PollForm
    model = Poll
    template_name = 'poll/create.html'

    def get_success_url(self):
        return reverse('poll_view', kwargs={'pk': self.object.pk})


class PollUpdateView(UpdateView):
    model = Poll
    template_name = 'poll/update.html'
    form_class = PollForm
    context_object_name = 'poll'

    def get_success_url(self):
        return reverse('poll_view', kwargs={'pk': self.object.pk})


class PollDeleteView(DeleteView):
    template_name = 'poll/delete.html'
    model = Poll
    context_object_name = 'poll'
    success_url = reverse_lazy('index')


class StatisticView(View):
    def get(self, request, *args, **kwargs):
        poll = Poll.objects.get(pk=kwargs.get('pk'))
        choices = poll.polls.all()

        print(Answer.objects.count())
        for choice in choices:
            print(len(Answer.objects.filter(choice__in=[choice.pk])))
        context = {'poll': poll, 'choices': choices}
        return render(request, 'poll/statistic.html', context=context)

source/webapp/templates/answer/answer.html
{% extends 'base.html' %}

{% block title %}Answers{% endblock %}

{% block content %}

    <h2>Answers:</h2>
    <div class="choice-list">

        <div class="choice">
            <h4>{{ poll.question }}</h4>
            <hr>
            <form method="POST" action="{% url 'answer' poll.pk %}">
                {% csrf_token %}
                {% for choice in poll.polls.all %}
                    <p>
                        <input type="radio"  name="choice" value="{{ choice.pk }}">
                        <label for="choice">{{ choice }}</label>
                    </p>
                {% endfor %}
                <div>
                    <button type="submit">Submit</button>
                </div>
            </form>

        </div>

    </div>
{% endblock %}

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MySite{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <ul class="menu">
                <li><a href="{% url 'index' %}">Home</a></li>
                {% block menu %}{% endblock %}
            </ul>
        </div>
    </nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/choice/create.html
{% extends 'base.html' %}

{% block title %}Create Comment{% endblock %}

{% block content %}
    <h1>Create Comment</h1>
    <form method="POST" action="">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/choice/delete.html
{% extends 'base.html' %}

{% block title %}Delete choice{% endblock %}

{% block content %}
    <h4>Are you sure want to delete the choice: "{{ choice.answer_option }}"?</h4>
    <form method="POST" action="{% url 'choice_delete' choice.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
        <p><a href="{% url 'poll_view' choice.poll.pk %}">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/choice/update.html
{% extends 'base.html' %}

{% block title %}Update Choice{% endblock %}

{% block content %}
    <h1>Update Choice</h1>
    <form method="POST" action="{% url 'choice_update' choice.pk %}">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}

source/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="form-error">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    <p>{{ field }}</p>
    {% for error in field.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
{% endfor %}

<p><input type="submit" value="{{ button_text }}"></p>

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <form action="" method="GET">
        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; В начало</a>

        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}

        <span>
            Страница <input class="page-input" type="text" name="page" value="{{ page_obj.number }}" maxlength="5"> из {{ paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}

        <a href="?{% if query %}{{ query }}&{% endif %}page={{ paginator.num_pages }}">В конец &raquo;</a>
    </form>
    <div>
        {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
                <span class="page-active">{{ page }}</span>
            {% else %}
                <a href="?{% if query %}{{ query }}&{% endif %}page={{ page }}">{{ page }}</a>
            {% endif %}
        {% endfor %}
    </div>
</div>

source/webapp/templates/poll/create.html
{% extends 'base.html' %}

{% block title %}Create Poll{% endblock %}

{% block content %}
    <h1>Create Article</h1>
    <form method="POST" action="{% url 'poll_add' %}">
        {% include 'partial/form.html' with button_text="Create" %}
    </form>
{% endblock %}

source/webapp/templates/poll/delete.html
{% extends 'base.html' %}

{% block title %}Delete Article{% endblock %}

{% block menu %}
    <li><a href="{% url 'poll_view' poll.pk %}">View</a></li>
{% endblock %}

{% block content %}
    <h4>Are you sure want to delete the poll: "{{ poll.question }}"</h4>
    <form method="POST" action="{% url 'poll_delete' poll.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
        <p><a href="{% url 'poll_view' poll.pk %}">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/poll/index.html
{% extends 'base.html' %}

{% block menu %}
    <li><a href="{% url 'poll_add' %}">Add Poll</a></li>
{% endblock %}

{% block content %}
    <section>
        <h1>Polls:</h1>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% include 'poll/partial/poll_list.html' %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </section>
{% endblock %}

source/webapp/templates/poll/partial/poll_list.html
<hr/>
{% for poll in polls %}
    <h4>{{ poll.question }}</h4>
    <p>
        <a href="{% url 'poll_view' poll.pk %}">More...</a>
        <a href="{% url 'poll_update' poll.pk %}">Edit</a>
        <a href="{% url 'poll_delete' poll.pk %}">Delete</a>
        <a href="{% url 'answer' poll.pk %}">Answer</a>
        <a href="{% url 'statistic' poll.pk %}">Stat info</a>
    </p>
    <hr/>
{% endfor %}

source/webapp/templates/poll/poll.html
{% extends 'base.html' %}

{% block title %}{{ poll.question }}{% endblock %}

{% block menu %}
    <li><a href="{% url 'poll_update' poll.pk%}">Edit</a></li>
    <li><a href="{% url 'poll_delete' poll.pk%}">Delete</a></li>
    <li><a href="{% url 'answer' poll.pk %}">Answer</a></li>
{% endblock %}

{% block content %}
    <h4>Question: {{ poll.question }}</h4>
    <p>Created at {{ poll.created_at|date:'d.m.Y H:i:s' }}</p>
    <hr/>
    <h4>Choices:</h4>
    <div class="choice-list">
        {% for choice in choices %}
            <div class="choice">
                <p>{{ choice.answer_option }}</p>
                    <p class="choice-links">
                        <a href="{% url 'choice_update' choice.pk %}">Edit</a>
                        <a href="{% url 'choice_delete' choice.pk %}">Delete</a>
                    </p>
            </div>
        {% endfor %}
    </div>
    <form action="{% url 'choice_add' poll.pk %}" method="POST" id="add_comment">
            {% include 'partial/form.html' with button_text='Add' %}
        </form>
{% endblock %}

source/webapp/templates/poll/statistic.html
{% extends 'base.html' %}

{% block title %}Statistic{% endblock %}

{% block content %}

    <h2>Answers:</h2>

{% endblock %}

source/webapp/templates/poll/update.html
{% extends 'base.html' %}

{% block title %}Update Poll{% endblock %}

{% block menu %}
    <li><a href="{% url 'poll_view' poll.pk %}">View</a></li>
{% endblock %}

{% block content %}
    <h1>Update Poll</h1>
    <form method="POST" action="{% url 'poll_update' poll.pk %}">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}